language: rust
cache: cargo
rust:
- stable
- beta
- nightly
env:
  global:
  - secure: Az8WPF9TLSs1StQjNlTJythqiMVbpnOjs+Q2L7/bDuDnsQBKQqfTOD7Xk2uR1+gs2nA/uMhNfY6yVM01sSfXbBhd1wQ3larPokCs11TPoTABPZA/+U8GqCwHazdgCknp0SMPjintrLLp0ISujzAA5485WKb2Xp7mUo7mIBwjACyqsacvTYBQrfeeR/YyXyyFXy+NrrXD4izEVLQ7Rin8wxsL/WtWJL+N0VWQ+cYmhibYlrDtlxdkVFvhNfefMwyluNUubtYf4NHE57MBBCiqRpAPBk3xI/912Vfv7fl0nOLLqjiV82CFrFkVCASho1MlpAFG8MfL4QO5xd9as7yudcuhbhUNK+FLRkyoSJfYAyTRyVkvhGirbsnBHLePdFiuHsThQO3OzdyOziXRBxRGUvDHAW9Bm02fwPbh+lWFsJvJVZInoamkIdzyJoMS6xTHmX11vtt8wGtCl4U/W/FjT/YOy/TNqRwUVkVzKzVRuHce8X6LSilACot1oXI8yoLX7WHhGmBRB1d6CqhVn34SP24rwepgMTfh3KbYph/FHW9YmZUEEkD7XWhAQpHm0G3qNLeH4keUzAf4W2+4sc4J5SvR+mvaavTciIVtg1hGpPTN7IOBfrbnXpSMXM9xzB4X5EhV/bmyKXm/g84UsKrYSFnmglQo3ACt1EarpD3vNPA=
  - secure: eHqIzdANpJoXYa0q3EUjreuqXqeIz13saXz3406bmM0G/n3Ua3/4/XgNP9FltMvgKzgfjYOLQhLnwcCNq/MAJJskHtz/j299c+LpcdpjNHD/4PHbCuuIQ2GM8yegHkP4rs1Mc74vEiEoRJ1LFeCWogxpwSWJdpmJOA+cpF5unWf4CxtvWar2dbUY6xVtvGEtP+c8JJIHIij1xCZqmpyRZIwrBmNAtvMnBg8wL4ujK3Hq00OyzsH2/SLnfPNxmL8iqg7WguFDDaz+zbCI/rp+1fBdjnpR2WE98VW9dm0eOeH3pw9lsupEtWH3pANlOMiGUeKoHV/utW86xJRmiXDp6hSce1gJVDglv/AeZv04aNLKTnrjkwXSSrfv1ofXywhsQ6amvxMEjPDFQccGQCf1KpFnpWp/lB9nsB0J8r9zH7o9Tk/OBcXdOtPdjPhbt6oCORIha+Ei0Q75JtR8T9LWWT8WZNSYYVwFJoPMtNW0DN3hqdfRocNEWIRVu45htYOxYQkpjJ94DVdnf6pIZL49+f6gCzrK3CeE61i3ZRCz07RbYhL2xMrH5/2KoKljykCWcH+NesOkTWp76IJM4PvEYH+R3/Ur2bCoiGYdG/zEG+xjzjSnL7JGNs/P9VWCAiBXDA1m+eQL8yvg32fIf3J98sXKhPa0MH2C2MaBtZynPQA=
after_success: |
  git clone https://gist.github.com/deaf3815d2eecce72279.git ./publish_doc &&
  sh ./publish_doc/publish_doc.sh shrust
